### ISSUE TITLE
Remove MyProjectManagerListener.kt

### ISSUE THREAD

**Issue by karollewandowski** [Olof-IL/RecentTabOrder#1]
Hi,
Please remove:
https://github.com/Olof-IL/RecentTabOrder/blob/master/src/main/kotlin/se/illusionlabs/recenttaborder/MyProjectManagerListener.kt
and its registration in the plugin.xml.

This listener throws an exception after opening projects.

**Comment by Olof-IL** [comment]
Thank you for your feedback.

What is the exception thrown?

The listener is there to make sure the ProjectService is loaded, if I remove the listener the service will never load...

This is my first IntelliJ plugin though, so it's possible I have misunderstood something about how it is supposed to be loaded, if you have any more info on this, please let me know.

**Comment by karollewandowski** [comment]
Hi,
When I filed this issue, it was the file state:
https://github.com/Olof-IL/RecentTabOrder/blob/7b566b3cbc3e04526b54b6b4468a155deb2f4ac5/src/main/kotlin/se/illusionlabs/recenttaborder/MyProjectManagerListener.kt

```
TODO("Don't forget to remove all non-needed sample code files with their corresponding registration entries in `plugin.xml`.")
```

I thought it was a leftover from the former template service:
https://github.com/JetBrains/intellij-platform-plugin-template/blob/b8ad6a9a5e55f08f56e423d49f3b743045a25fcb/src/main/kotlin/org/jetbrains/plugins/template/services/MyProjectService.kt#L14:L15

but I didn't notice you commented it out partially, so it should work. Anyway, it's better not to leave `TODO()`.
Now it looks fine.

**Comment by Olof-IL** [comment]
It was indeed some leftovers, and I totally agree so it's gone now. Glad to hear it wasn't anything more serious.
