### ISSUE TITLE
Incompatible with latest version of CLion

### ISSUE THREAD

**Issue by Daskie** [Olof-IL/RecentTabOrder#2]
I've gotten this since the last CLion update:

![image](https://github.com/Olof-IL/RecentTabOrder/assets/5835795/3e64f8dc-b1f0-4deb-a618-5b7399e30dd2)

Love this plugin by the way! It's so good for productivity, I can't believe this isn't a built-in feature.

CLion 2023.2
Build #CL-232.8660.186, built on July 25, 2023

**Comment by Olof-IL** [comment]
Thank you for the report. I'll look into it

**Comment by Olof-IL** [comment]
It seems the problem was just a version check, I've removed the "until-version" and uploaded a new version 1.0.3, that should work with CLion (and all future version until they change some API I'm using...)

**Comment by Daskie** [comment]
Works a charm, thank you!
